# Generated by Django 5.1.3 on 2024-11-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.EmailField(max_length=254, unique=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('disciplines', models.CharField(choices=[('music', 'music'), ('dance', 'dance'), ('drama', 'drama')], max_length=20)),
                ('mailaddress', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('schools', models.ManyToManyField(related_name='teachers', to='lookup.school', verbose_name='school where this person teaches')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=800)),
                ('schedule', models.DateTimeField()),
                ('target_audience', models.CharField(choices=[('anyone', 'Anyone'), ('elderly', 'Elderly'), ('adults', 'Adults'), ('adolescents', 'Adolescents'), ('children', 'Children')], default='anyone', max_length=20)),
                ('discipline', models.CharField(choices=[('music', 'music'), ('dance', 'dance'), ('drama', 'drama')])),
                ('online', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lookup.school', verbose_name='where the course takes place')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lookup.school', verbose_name='school where the course takes place')),
                ('teachers', models.ManyToManyField(related_name='courses', to='lookup.teacher')),
            ],
        ),
    ]
