# Generated by Django 5.1.3 on 2024-12-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
    ]
