# Generated by Django 5.1.3 on 2025-01-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_course_students_alter_course_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
