# Generated by Django 5.1.3 on 2025-01-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_course_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='archived',
        ),
    ]
