# Generated by Django 5.1.3 on 2025-02-16 19:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0010_alter_school_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
